name: Playwright Tests

on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # Este cron ejecuta el workflow todos los domingos a medianoche UTC
  workflow_dispatch:  # Permite ejecutar el flujo de trabajo manualmente desde la interfaz de GitHub


jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    - name: Run tests on desktop
      run: |
        pytest --capture=tee-sys --html=resultsdesktop.html --self-contained-html --device="Desktop Chrome" --video=on

    - name: Upload Playwright report (Desktop)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-desktop
        path: resultsdesktop.html

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-videos-traces
        path: test-results/

